#!/usr/bin/env python
import logging

import card_live_dashboard

if __name__ == '__main__':
    app = card_live_dashboard.build_app()
    app.run_server(debug = True,
                  port = 8050,
                  host = '0.0.0.0')

