#!/usr/bin/env python
import logging

import card_live_dashboard.app

if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG,
                        format='[%(asctime)s] [%(levelname)s] %(module)s.%(funcName)s,%(lineno)s: %(message)s')
    app = card_live_dashboard.app.build_app()
    app.run_server(debug = False,
                  port = 8050,
                  host = '0.0.0.0')

